In [5]:
import os
import pandas as pd
from google.cloud import bigquery
import db_dtypes

#scenic-outcome-453219-h5-4c318c9a7175
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="scenic-outcome-453219-h5-4c318c9a7175.json"
client = bigquery.Client() 

pd.set_option('display.max_columns', None)  # wyłącz limit na kolumny
pd.set_option('display.max_rows', None)  # wyłącz limit na wiersze
pd.set_option('display.width', None)  # wyłącz limit na szerokość
pd.set_option('display.max_colwidth', None)  # wyłącz limit na szerokość kolumn
# client = bigquery.Client()

In [6]:
query = ('select * from bigquery-public-data.covid19_open_data.covid19_open_data')
query_job = client.query(query)
query_result = query_job.result()
df = query_result.to_dataframe()

In [35]:
df

,location_key,date,place_id,wikidata_id,datacommons_id,country_code,country_name,iso_3166_1_alpha_2,iso_3166_1_alpha_3,aggregation_level,new_confirmed,new_deceased,cumulative_confirmed,cumulative_deceased,cumulative_tested,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered,population,population_male,population_female,population_rural,population_urban,population_density,human_development_index,population_age_00_09,population_age_10_19,population_age_20_29,population_age_30_39,population_age_40_49,population_age_50_59,population_age_60_69,population_age_70_79,population_age_80_and_older,gdp_usd,gdp_per_capita_usd,openstreetmap_id,latitude,longitude,area_sq_km,smoking_prevalence,diabetes_prevalence,infant_mortality_rate,nurses_per_1000,physicians_per_1000,health_expenditure_usd,out_of_pocket_health_expenditure_usd,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,income_support,debt_relief,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index,average_temperature_celsius,minimum_temperature_celsius,maximum_temperature_celsius,rainfall_mm,snowfall_mm,dew_point,relative_humidity,new_tested,population_largest_city,population_clustered,human_capital_index,area_rural_sq_km,area_urban_sq_km,life_expectancy,adult_male_mortality_rate,adult_female_mortality_rate,pollution_mortality_rate,comorbidity_mortality_rate,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,hospital_beds_per_1000,subregion1_code,subregion1_name,new_recovered,cumulative_recovered,elevation_m,new_hospitalized_patients,cumulative_hospitalized_patients,new_intensive_care_patients,cumulative_intensive_care_patients,new_confirmed_age_0,new_confirmed_age_1,new_confirmed_age_2,new_confirmed_age_3,new_confirmed_age_4,new_confirmed_age_5,new_confirmed_age_6,new_confirmed_age_7,new_confirmed_age_8,new_confirmed_age_9,cumulative_confirmed_age_0,cumulative_confirmed_age_1,cumulative_confirmed_age_2,cumulative_confirmed_age_3,cumulative_confirmed_age_4,cumulative_confirmed_age_5,cumulative_confirmed_age_6,cumulative_confirmed_age_7,cumulative_confirmed_age_8,cumulative_confirmed_age_9,new_deceased_age_0,new_deceased_age_1,new_deceased_age_2,new_deceased_age_3,new_deceased_age_4,new_deceased_age_5,new_deceased_age_6,new_deceased_age_7,new_deceased_age_8,new_deceased_age_9,cumulative_deceased_age_0,cumulative_deceased_age_1,cumulative_deceased_age_2,cumulative_deceased_age_3,cumulative_deceased_age_4,cumulative_deceased_age_5,cumulative_deceased_age_6,cumulative_deceased_age_7,cumulative_deceased_age_8,cumulative_deceased_age_9,new_tested_age_0,new_tested_age_1,new_tested_age_2,new_tested_age_3,new_tested_age_4,new_tested_age_5,new_tested_age_6,new_tested_age_7,new_tested_age_8,new_tested_age_9,cumulative_tested_age_0,cumulative_tested_age_1,cumulative_tested_age_2,cumulative_tested_age_3,cumulative_tested_age_4,cumulative_tested_age_5,cumulative_tested_age_6,cumulative_tested_age_7,cumulative_tested_age_8,cumulative_tested_age_9,new_hospitalized_patients_age_0,new_hospitalized_patients_age_1,new_hospitalized_patients_age_2,new_hospitalized_patients_age_3,new_hospitalized_patients_age_4,new_hospitalized_patients_age_5,new_hospitalized_patients_age_6,new_hospitalized_patients_age_7,new_hospitalized_patients_age_8,new_hospitalized_patients_age_9,cumulative_hospitalized_patients_age_0,cumulative_hospitalized_patients_age_1,cumulative_hospitalized_patients_age_2,cumulative_hospitalized_patients_age_3,cumulative_hospitalized_patients_age_4,cumulative_hospitalized_patients_age_5,cumulative_hospitalized_patients_age_6,cumulative_hospitalized_patients_age_7,cumulative_hospitalized_patients_age_8,cumulative_hospitalized_patients_age_9,new_intensive_care_patients_age_0,new_intensive_care_patients_age_1,new_intensive_care_patients_age_2,new_intensive_care_patients_age_3,new_intensive_care_patients_age_4,new_intensive_care_patients_age_5,new_intensive_care_patients_age_6,new_intensive_care_patients_age_7,new_intensive_care_patients_age_8,new_intensive_care_patients_age_9,cumulative_intensive_care_patients_age_0,cumulative_intensive_care_patients_age_1,cumulative_intensive_care_patients_age_2,cumulative_intensive_care_patients_age_3,cumulative_intensive_care_patients_age_4,cumulative_intensive_care_patients_age_5,cumulative_intensive_care_patients_age_6,cumulative_intensive_care_patients_age_7,cumulative_intensive_care_patients_age_8,cumulative_intensive_care_patients_age_9,age_bin_0,age_bin_1,age_bin_2,age_bin_3,age_bin_4,age_bin_5,age_bin_6,age_bin_7,age_bin_8,age_bin_9,new_confirmed_male,new_confirmed_female,cumulative_confirmed_male,cumulative_confirmed_female,new_deceased_male,new_deceased_female,cumulative_deceased_male,cumulative_deceased_female,new_tested_male,new_tested_female,cumulative_tested_male,cumulative_tested_female,new_hospitalized_patients_male,new_hospitalized_patients_female,cumulative_hospitalized_patients_male,cumulative_hospitalized_patients_female,new_intensive_care_patients_male,new_intensive_care_patients_female,cumulative_intensive_care_patients_male,cumulative_intensive_care_patients_female,subregion2_code,subregion2_name,current_hospitalized_patients,current_intensive_care_patients,current_ventilator_patients,search_trends_abdominal_obesity,search_trends_abdominal_pain,search_trends_acne,search_trends_actinic_keratosis,search_trends_acute_bronchitis,search_trends_adrenal_crisis,search_trends_ageusia,search_trends_alcoholism,search_trends_allergic_conjunctivitis,search_trends_allergy,search_trends_amblyopia,search_trends_amenorrhea,search_trends_amnesia,search_trends_anal_fissure,search_trends_anaphylaxis,search_trends_anemia,search_trends_angina_pectoris,search_trends_angioedema,search_trends_angular_cheilitis,search_trends_anosmia,search_trends_anxiety,search_trends_aphasia,search_trends_aphonia,search_trends_apnea,search_trends_arthralgia,search_trends_arthritis,search_trends_ascites,search_trends_asperger_syndrome,search_trends_asphyxia,search_trends_asthma,search_trends_astigmatism,search_trends_ataxia,search_trends_atheroma,search_trends_attention_deficit_hyperactivity_disorder,search_trends_auditory_hallucination,search_trends_autoimmune_disease,search_trends_avoidant_personality_disorder,search_trends_back_pain,search_trends_bacterial_vaginosis,search_trends_balance_disorder,search_trends_beaus_lines,search_trends_bells_palsy,search_trends_biliary_colic,search_trends_binge_eating,search_trends_bleeding,search_trends_bleeding_on_probing,search_trends_blepharospasm,search_trends_bloating,search_trends_blood_in_stool,search_trends_blurred_vision,search_trends_blushing,search_trends_boil,search_trends_bone_fracture,search_trends_bone_tumor,search_trends_bowel_obstruction,search_trends_bradycardia,search_trends_braxton_hicks_contractions,search_trends_breakthrough_bleeding,search_trends_breast_pain,search_trends_bronchitis,search_trends_bruise,search_trends_bruxism,search_trends_bunion,search_trends_burn,search_trends_burning_chest_pain,search_trends_burning_mouth_syndrome,search_trends_candidiasis,search_trends_canker_sore,search_trends_cardiac_arrest,search_trends_carpal_tunnel_syndrome,search_trends_cataplexy,search_trends_cataract,search_trends_chancre,search_trends_cheilitis,search_trends_chest_pain,search_trends_chills,search_trends_chorea,search_trends_chronic_pain,search_trends_cirrhosis,search_trends_cleft_lip_and_cleft_palate,search_trends_clouding_of_consciousness,search_trends_cluster_headache,search_trends_colitis,search_trends_coma,search_trends_common_cold,search_trends_compulsive_behavior,search_trends_compulsive_hoarding,search_trends_confusion,search_trends_congenital_heart_defect,search_trends_conjunctivitis,search_trends_constipation,search_trends_convulsion,search_trends_cough,search_trends_crackles,search_trends_cramp,search_trends_crepitus,search_trends_croup,search_trends_cyanosis,search_trends_dandruff,search_trends_delayed_onset_muscle_soreness,search_trends_dementia,search_trends_dentin_hypersensitivity,search_trends_depersonalization,search_trends_depression,search_trends_dermatitis,search_trends_desquamation,search_trends_developmental_disability,search_trends_diabetes,search_trends_diabetic_ketoacidosis,search_trends_diarrhea,search_trends_dizziness,search_trends_dry_eye_syndrome,search_trends_dysautonomia,search_trends_dysgeusia,search_trends_dysmenorrhea,search_trends_dyspareunia,search_trends_dysphagia,search_trends_dysphoria,search_trends_dystonia,search_trends_dysuria,search_trends_ear_pain,search_trends_eczema,search_trends_edema,search_trends_encephalitis,search_trends_encephalopathy,search_trends_epidermoid_cyst,search_trends_epilepsy,search_trends_epiphora,search_trends_erectile_dysfunction,search_trends_erythema,search_trends_erythema_chronicum_migrans,search_trends_esophagitis,search_trends_excessive_daytime_sleepiness,search_trends_eye_pain,search_trends_eye_strain,search_trends_facial_nerve_paralysis,search_trends_facial_swelling,search_trends_fasciculation,search_trends_fatigue,search_trends_fatty_liver_disease,search_trends_fecal_incontinence,search_trends_fever,search_trends_fibrillation,search_trends_fibrocystic_breast_changes,search_trends_fibromyalgia,search_trends_flatulence,search_trends_floater,search_trends_focal_seizure,search_trends_folate_deficiency,search_trends_food_craving,search_trends_food_intolerance,search_trends_frequent_urination,search_trends_gastroesophageal_reflux_disease,search_trends_gastroparesis,search_trends_generalized_anxiety_disorder,search_trends_genital_wart,search_trends_gingival_recession,search_trends_gingivitis,search_trends_globus_pharyngis,search_trends_goitre,search_trends_gout,search_trends_grandiosity,search_trends_granuloma,search_trends_guilt,search_trends_hair_loss,search_trends_halitosis,search_trends_hay_fever,search_trends_headache,search_trends_heart_arrhythmia,search_trends_heart_murmur,search_trends_heartburn,search_trends_hematochezia,search_trends_hematoma,search_trends_hematuria,search_trends_hemolysis,search_trends_hemoptysis,search_trends_hemorrhoids,search_trends_hepatic_encephalopathy,search_trends_hepatitis,search_trends_hepatotoxicity,search_trends_hiccup,search_trends_hip_pain,search_trends_hives,search_trends_hot_flash,search_trends_hydrocephalus,search_trends_hypercalcaemia,search_trends_hypercapnia,search_trends_hypercholesterolemia,search_trends_hyperemesis_gravidarum,search_trends_hyperglycemia,search_trends_hyperhidrosis,search_trends_hyperkalemia,search_trends_hyperlipidemia,search_trends_hypermobility,search_trends_hyperpigmentation,search_trends_hypersomnia,search_trends_hypertension,search_trends_hyperthermia,search_trends_hyperthyroidism,search_trends_hypertriglyceridemia,search_trends_hypertrophy,search_trends_hyperventilation,search_trends_hypocalcaemia,search_trends_hypochondriasis,search_trends_hypoglycemia,search_trends_hypogonadism,search_trends_hypokalemia,search_trends_hypomania,search_trends_hyponatremia,search_trends_hypotension,search_trends_hypothyroidism,search_trends_hypoxemia,search_trends_hypoxia,search_trends_impetigo,search_trends_implantation_bleeding,search_trends_impulsivity,search_trends_indigestion,search_trends_infection,search_trends_inflammation,search_trends_inflammatory_bowel_disease,search_trends_ingrown_hair,search_trends_insomnia,search_trends_insulin_resistance,search_trends_intermenstrual_bleeding,search_trends_intracranial_pressure,search_trends_iron_deficiency,search_trends_irregular_menstruation,search_trends_itch,search_trends_jaundice,search_trends_kidney_failure,search_trends_kidney_stone,search_trends_knee_pain,search_trends_kyphosis,search_trends_lactose_intolerance,search_trends_laryngitis,search_trends_leg_cramps,search_trends_lesion,search_trends_leukorrhea,search_trends_lightheadedness,search_trends_low_back_pain,search_trends_low_grade_fever,search_trends_lymphedema,search_trends_major_depressive_disorder,search_trends_malabsorption,search_trends_male_infertility,search_trends_manic_disorder,search_trends_melasma,search_trends_melena,search_trends_meningitis,search_trends_menorrhagia,search_trends_middle_back_pain,search_trends_migraine,search_trends_milium,search_trends_mitral_insufficiency,search_trends_mood_disorder,search_trends_mood_swing,search_trends_morning_sickness,search_trends_motion_sickness,search_trends_mouth_ulcer,search_trends_muscle_atrophy,search_trends_muscle_weakness,search_trends_myalgia,search_trends_mydriasis,search_trends_myocardial_infarction,search_trends_myoclonus,search_trends_nasal_congestion,search_trends_nasal_polyp,search_trends_nausea,search_trends_neck_mass,search_trends_neck_pain,search_trends_neonatal_jaundice,search_trends_nerve_injury,search_trends_neuralgia,search_trends_neutropenia,search_trends_night_sweats,search_trends_night_terror,search_trends_nocturnal_enuresis,search_trends_nodule,search_trends_nosebleed,search_trends_nystagmus,search_trends_obesity,search_trends_onychorrhexis,search_trends_oral_candidiasis,search_trends_orthostatic_hypotension,search_trends_osteopenia,search_trends_osteophyte,search_trends_osteoporosis,search_trends_otitis,search_trends_otitis_externa,search_trends_otitis_media,search_trends_pain,search_trends_palpitations,search_trends_pancreatitis,search_trends_panic_attack,search_trends_papule,search_trends_paranoia,search_trends_paresthesia,search_trends_pelvic_inflammatory_disease,search_trends_pericarditis,search_trends_periodontal_disease,search_trends_periorbital_puffiness,search_trends_peripheral_neuropathy,search_trends_perspiration,search_trends_petechia,search_trends_phlegm,search_trends_photodermatitis,search_trends_photophobia,search_trends_photopsia,search_trends_pleural_effusion,search_trends_pleurisy,search_trends_pneumonia,search_trends_podalgia,search_trends_polycythemia,search_trends_polydipsia,search_trends_polyneuropathy,search_trends_polyuria,search_trends_poor_posture,search_trends_post_nasal_drip,search_trends_postural_orthostatic_tachycardia_syndrome,search_trends_prediabetes,search_trends_proteinuria,search_trends_pruritus_ani,search_trends_psychosis,search_trends_ptosis,search_trends_pulmonary_edema,search_trends_pulmonary_hypertension,search_trends_purpura,search_trends_pus,search_trends_pyelonephritis,search_trends_radiculopathy,search_trends_rectal_pain,search_trends_rectal_prolapse,search_trends_red_eye,search_trends_renal_colic,search_trends_restless_legs_syndrome,search_trends_rheum,search_trends_rhinitis,search_trends_rhinorrhea,search_trends_rosacea,search_trends_round_ligament_pain,search_trends_rumination,search_trends_scar,search_trends_sciatica,search_trends_scoliosis,search_trends_seborrheic_dermatitis,search_trends_self_harm,search_trends_sensitivity_to_sound,search_trends_sexual_dysfunction,search_trends_shallow_breathing,search_trends_sharp_pain,search_trends_shivering,search_trends_shortness_of_breath,search_trends_shyness,search_trends_sinusitis,search_trends_skin_condition,search_trends_skin_rash,search_trends_skin_tag,search_trends_skin_ulcer,search_trends_sleep_apnea,search_trends_sleep_deprivation,search_trends_sleep_disorder,search_trends_snoring,search_trends_sore_throat,search_trends_spasticity,search_trends_splenomegaly,search_trends_sputum,search_trends_stomach_rumble,search_trends_strabismus,search_trends_stretch_marks,search_trends_stridor,search_trends_stroke,search_trends_stuttering,search_trends_subdural_hematoma,search_trends_suicidal_ideation,search_trends_swelling,search_trends_swollen_feet,search_trends_swollen_lymph_nodes,search_trends_syncope,search_trends_tachycardia,search_trends_tachypnea,search_trends_telangiectasia,search_trends_tenderness,search_trends_testicular_pain,search_trends_throat_irritation,search_trends_thrombocytopenia,search_trends_thyroid_nodule,search_trends_tic,search_trends_tinnitus,search_trends_tonsillitis,search_trends_toothache,search_trends_tremor,search_trends_trichoptilosis,search_trends_tumor,search_trends_type_2_diabetes,search_trends_unconsciousness,search_trends_underweight,search_trends_upper_respiratory_tract_infection,search_trends_urethritis,search_trends_urinary_incontinence,search_trends_urinary_tract_infection,search_trends_urinary_urgency,search_trends_uterine_contraction,search_trends_vaginal_bleeding,search_trends_vaginal_discharge,search_trends_vaginitis,search_trends_varicose_veins,search_trends_vasculitis,search_trends_ventricular_fibrillation,search_trends_ventricular_tachycardia,search_trends_vertigo,search_trends_viral_pneumonia,search_trends_visual_acuity,search_trends_vomiting,search_trends_wart,search_trends_water_retention,search_trends_weakness,search_trends_weight_gain,search_trends_wheeze,search_trends_xeroderma,search_trends_xerostomia,search_trends_yawn,new_recovered_age_0,new_recovered_age_1,new_recovered_age_2,new_recovered_age_3,new_recovered_age_4,new_recovered_age_5,new_recovered_age_6,new_recovered_age_7,new_recovered_age_8,new_recovered_age_9,cumulative_recovered_age_0,cumulative_recovered_age_1,cumulative_recovered_age_2,cumulative_recovered_age_3,cumulative_recovered_age_4,cumulative_recovered_age_5,cumulative_recovered_age_6,cumulative_recovered_age_7,cumulative_recovered_age_8,cumulative_recovered_age_9,new_recovered_male,new_recovered_female,cumulative_recovered_male,cumulative_recovered_female,locality_code,locality_name,new_ventilator_patients,cumulative_ventilator_patients,new_persons_fully_vaccinated_pfizer,cumulative_persons_fully_vaccinated_pfizer,new_vaccine_doses_administered_pfizer,cumulative_vaccine_doses_administered_pfizer,new_persons_fully_vaccinated_moderna,cumulative_persons_fully_vaccinated_moderna,new_vaccine_doses_administered_moderna,cumulative_vaccine_doses_administered_moderna,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,location_geometry

In [3]:
#Lista wszystkich kolumn
query = """
    SELECT column_name
    FROM `bigquery-public-data.covid19_open_data.INFORMATION_SCHEMA.COLUMNS`
    WHERE table_name = 'covid19_open_data'
"""
query_job = client.query(query)
columns_df = query_job.result().to_dataframe()

columns_df

                                                 column_name
0                                               location_key
1                                                       date
2                                                   place_id
3                                                wikidata_id
4                                             datacommons_id
5                                               country_code
6                                               country_name
7                                         iso_3166_1_alpha_2
8                                         iso_3166_1_alpha_3
9                                          aggregation_level
10                                             new_confirmed
11                                              new_deceased
12                                      cumulative_confirmed
13                                       cumulative_deceased
14                                         cumulative_tested
15                                    new_persons_vaccinated
16                             cumulative_persons_vaccinated
17                              new_persons_fully_vaccinated
18                       cumulative_persons_fully_vaccinated
19                            new_vaccine_doses_administered
20                     cumulative_vaccine_doses_administered
21                                                population
22                                           population_male
23                                         population_female
24                                          population_rural
25                                          population_urban
26                                        population_density
27                                   human_development_index
28                                      population_age_00_09
29                                      population_age_10_19
30                                      population_age_20_29
31                                      population_age_30_39
32                                      population_age_40_49
33                                      population_age_50_59
34                                      population_age_60_69
35                                      population_age_70_79
36                               population_age_80_and_older
37                                                   gdp_usd
38                                        gdp_per_capita_usd
39                                          openstreetmap_id
40                                                  latitude
41                                                 longitude
42                                                area_sq_km
43                                        smoking_prevalence
44                                       diabetes_prevalence
45                                     infant_mortality_rate
46                                           nurses_per_1000
47                                       physicians_per_1000
48                                    health_expenditure_usd
49                      out_of_pocket_health_expenditure_usd
50                                            school_closing
51                                         workplace_closing
52                                      cancel_public_events
53                                restrictions_on_gatherings
54                                  public_transport_closing
55                                 stay_at_home_requirements
56                         restrictions_on_internal_movement
57                             international_travel_controls
58                                            income_support
59                                               debt_relief
60                                           fiscal_measures
61                                     international_support
62                              public_information_campaigns
63                                            testing_policy
64                                           contact_tracing
65                        emergency_investment_in_healthcare
66                                    investment_in_vaccines
67                                          facial_coverings
68                                        vaccination_policy
69                                          stringency_index
70                               average_temperature_celsius
71                               minimum_temperature_celsius
72                               maximum_temperature_celsius
73                                               rainfall_mm
74                                               snowfall_mm
75                                                 dew_point
76                                         relative_humidity
77                                                new_tested
78                                   population_largest_city
79                                      population_clustered
80                                       human_capital_index
81                                          area_rural_sq_km
82                                          area_urban_sq_km
83                                           life_expectancy
84                                 adult_male_mortality_rate
85                               adult_female_mortality_rate
86                                  pollution_mortality_rate
87                                comorbidity_mortality_rate
88                            mobility_retail_and_recreation
89                             mobility_grocery_and_pharmacy
90                                            mobility_parks
91                                 mobility_transit_stations
92                                       mobility_workplaces
93                                      mobility_residential
94                                    hospital_beds_per_1000
95                                           subregion1_code
96                                           subregion1_name
97                                             new_recovered
98                                      cumulative_recovered
99                                               elevation_m
100                                new_hospitalized_patients
101                         cumulative_hospitalized_patients
102                              new_intensive_care_patients
103                       cumulative_intensive_care_patients
104                                      new_confirmed_age_0
105                                      new_confirmed_age_1
106                                      new_confirmed_age_2
107                                      new_confirmed_age_3
108                                      new_confirmed_age_4
109                                      new_confirmed_age_5
110                                      new_confirmed_age_6
111                                      new_confirmed_age_7
112                                      new_confirmed_age_8
113                                      new_confirmed_age_9
114                               cumulative_confirmed_age_0
115                               cumulative_confirmed_age_1
116                               cumulative_confirmed_age_2
117                               cumulative_confirmed_age_3
118                               cumulative_confirmed_age_4
119                               cumulative_confirmed_age_5
120                               cumulative_confirmed_age_6
121                               cumulative_confirmed_age_7
122                               cumulative_confirmed_age_8
123                               cumulative_confirmed_age_9
124                                       new_deceased_age_0
125                                       new_deceased_age_1
126                                       new_deceased_age_2
127                                       new_deceased_age_3
128                                       new_deceased_age_4
129                                       new_deceased_age_5
130                                       new_deceased_age_6
131                                       new_deceased_age_7
132                                       new_deceased_age_8
133                                       new_deceased_age_9
134                                cumulative_deceased_age_0
135                                cumulative_deceased_age_1
136                                cumulative_deceased_age_2
137                                cumulative_deceased_age_3
138                                cumulative_deceased_age_4
139                                cumulative_deceased_age_5
140                                cumulative_deceased_age_6
141                                cumulative_deceased_age_7
142                                cumulative_deceased_age_8
143                                cumulative_deceased_age_9
144                                         new_tested_age_0
145                                         new_tested_age_1
146                                         new_tested_age_2
147                                         new_tested_age_3
148                                         new_tested_age_4
149                                         new_tested_age_5
150                                         new_tested_age_6
151                                         new_tested_age_7
152                                         new_tested_age_8
153                                         new_tested_age_9
154                                  cumulative_tested_age_0
155                                  cumulative_tested_age_1
156                                  cumulative_tested_age_2
157                                  cumulative_tested_age_3
158                                  cumulative_tested_age_4
159                                  cumulative_tested_age_5
160                                  cumulative_tested_age_6
161                                  cumulative_tested_age_7
162                                  cumulative_tested_age_8
163                                  cumulative_tested_age_9
164                          new_hospitalized_patients_age_0
165                          new_hospitalized_patients_age_1
166                          new_hospitalized_patients_age_2
167                          new_hospitalized_patients_age_3
168                          new_hospitalized_patients_age_4
169                          new_hospitalized_patients_age_5
170                          new_hospitalized_patients_age_6
171                          new_hospitalized_patients_age_7
172                          new_hospitalized_patients_age_8
173                          new_hospitalized_patients_age_9
174                   cumulative_hospitalized_patients_age_0
175                   cumulative_hospitalized_patients_age_1
176                   cumulative_hospitalized_patients_age_2
177                   cumulative_hospitalized_patients_age_3
178                   cumulative_hospitalized_patients_age_4
179                   cumulative_hospitalized_patients_age_5
180                   cumulative_hospitalized_patients_age_6
181                   cumulative_hospitalized_patients_age_7
182                   cumulative_hospitalized_patients_age_8
183                   cumulative_hospitalized_patients_age_9
184                        new_intensive_care_patients_age_0
185                        new_intensive_care_patients_age_1
186                        new_intensive_care_patients_age_2
187                        new_intensive_care_patients_age_3
188                        new_intensive_care_patients_age_4
189                        new_intensive_care_patients_age_5
190                        new_intensive_care_patients_age_6
191                        new_intensive_care_patients_age_7
192                        new_intensive_care_patients_age_8
193                        new_intensive_care_patients_age_9
194                 cumulative_intensive_care_patients_age_0
195                 cumulative_intensive_care_patients_age_1
196                 cumulative_intensive_care_patients_age_2
197                 cumulative_intensive_care_patients_age_3
198                 cumulative_intensive_care_patients_age_4
199                 cumulative_intensive_care_patients_age_5
200                 cumulative_intensive_care_patients_age_6
201                 cumulative_intensive_care_patients_age_7
202                 cumulative_intensive_care_patients_age_8
203                 cumulative_intensive_care_patients_age_9
204                                                age_bin_0
205                                                age_bin_1
206                                                age_bin_2
207                                                age_bin_3
208                                                age_bin_4
209                                                age_bin_5
210                                                age_bin_6
211                                                age_bin_7
212                                                age_bin_8
213                                                age_bin_9
214                                       new_confirmed_male
215                                     new_confirmed_female
216                                cumulative_confirmed_male
217                              cumulative_confirmed_female
218                                        new_deceased_male
219                                      new_deceased_female
220                                 cumulative_deceased_male
221                               cumulative_deceased_female
222                                          new_tested_male
223                                        new_tested_female
224                                   cumulative_tested_male
225                                 cumulative_tested_female
226                           new_hospitalized_patients_male
227                         new_hospitalized_patients_female
228                    cumulative_hospitalized_patients_male
229                  cumulative_hospitalized_patients_female
230                         new_intensive_care_patients_male
231                       new_intensive_care_patients_female
232                  cumulative_intensive_care_patients_male
233                cumulative_intensive_care_patients_female
234                                          subregion2_code
235                                          subregion2_name
236                            current_hospitalized_patients
237                          current_intensive_care_patients
238                              current_ventilator_patients
239                          search_trends_abdominal_obesity
240                             search_trends_abdominal_pain
241                                       search_trends_acne
242                          search_trends_actinic_keratosis
243                           search_trends_acute_bronchitis
244                             search_trends_adrenal_crisis
245                                    search_trends_ageusia
246                                 search_trends_alcoholism
247                    search_trends_allergic_conjunctivitis
248                                    search_trends_allergy
249                                  search_trends_amblyopia
250                                 search_trends_amenorrhea
251                                    search_trends_amnesia
252                               search_trends_anal_fissure
253                                search_trends_anaphylaxis
254                                     search_trends_anemia
255                            search_trends_angina_pectoris
256                                 search_trends_angioedema
257                          search_trends_angular_cheilitis
258                                    search_trends_anosmia
259                                    search_trends_anxiety
260                                    search_trends_aphasia
261                                    search_trends_aphonia
262                                      search_trends_apnea
263                                 search_trends_arthralgia
264                                  search_trends_arthritis
265                                    search_trends_ascites
266                          search_trends_asperger_syndrome
267                                   search_trends_asphyxia
268                                     search_trends_asthma
269                                search_trends_astigmatism
270                                     search_trends_ataxia
271                                   search_trends_atheroma
272   search_trends_attention_deficit_hyperactivity_disorder
273                     search_trends_auditory_hallucination
274                         search_trends_autoimmune_disease
275              search_trends_avoidant_personality_disorder
276                                  search_trends_back_pain
277                        search_trends_bacterial_vaginosis
278                           search_trends_balance_disorder
279                                search_trends_beaus_lines
280                                search_trends_bells_palsy
281                              search_trends_biliary_colic
282                               search_trends_binge_eating
283                                   search_trends_bleeding
284                        search_trends_bleeding_on_probing
285                              search_trends_blepharospasm
286                                   search_trends_bloating
287                             search_trends_blood_in_stool
288                             search_trends_blurred_vision
289                                   search_trends_blushing
290                                       search_trends_boil
291                              search_trends_bone_fracture
292                                 search_trends_bone_tumor
293                          search_trends_bowel_obstruction
294                                search_trends_bradycardia
295                 search_trends_braxton_hicks_contractions
296                      search_trends_breakthrough_bleeding
297                                search_trends_breast_pain
298                                 search_trends_bronchitis
299                                     search_trends_bruise
300                                    search_trends_bruxism
301                                     search_trends_bunion
302                                       search_trends_burn
303                         search_trends_burning_chest_pain
304                     search_trends_burning_mouth_syndrome
305                                search_trends_candidiasis
306                                search_trends_canker_sore
307                             search_trends_cardiac_arrest
308                     search_trends_carpal_tunnel_syndrome
309                                  search_trends_cataplexy
310                                   search_trends_cataract
311                                    search_trends_chancre
312                                  search_trends_cheilitis
313                                 search_trends_chest_pain
314                                     search_trends_chills
315                                     search_trends_chorea
316                               search_trends_chronic_pain
317                                  search_trends_cirrhosis
318                 search_trends_cleft_lip_and_cleft_palate
319                  search_trends_clouding_of_consciousness
320                           search_trends_cluster_headache
321                                    search_trends_colitis
322                                       search_trends_coma
323                                search_trends_common_cold
324                        search_trends_compulsive_behavior
325                        search_trends_compulsive_hoarding

In [7]:
# 4.0
query = """
    select location_key, date, country_code, country_name,
    new_confirmed, new_deceased, cumulative_confirmed, cumulative_deceased,
    new_tested, cumulative_tested,
    new_recovered,
    new_persons_vaccinated, cumulative_persons_vaccinated,
    new_persons_fully_vaccinated, cumulative_persons_fully_vaccinated,
    new_vaccine_doses_administered, cumulative_vaccine_doses_administered
    population, population_male, population_female,
    population_density, human_development_index, gdp_usd, gdp_per_capita_usd,
    area_sq_km, health_expenditure_usd, vaccination_policy, stringency_index,
    life_expectancy, new_hospitalized_patients,
    population_age_00_09, population_age_10_19, population_age_20_29, population_age_30_39,
    population_age_40_49, population_age_50_59, population_age_60_69, population_age_70_79,
    population_age_80_and_older
    from `bigquery-public-data.covid19_open_data.covid19_open_data` 
    where aggregation_level = 0
"""
query_job = client.query(query)
df = query_job.result().to_dataframe()

df

In [ ]:
#4.01 czyszczenie danych
import numpy as np

# 1. Ogólne czyszczenie danych

# Konwersja kolumny date do formatu daty
df['date'] = pd.to_datetime(df['date'])

# Usunięcie duplikatów
df_clean = df.drop_duplicates()

# Usuwamy wiersze bez kluczowych informacji (np. brak kodu lub nazwy kraju)
df_clean = df_clean.dropna(subset=['country_code', 'country_name'])

# Ujednolicenie: ustawienie kodu kraju na wielkie litery
#df_clean['country_code'] = df_clean['country_code'].str.upper()

# Sprawdzamy dane liczbowe – ujemne wartości traktujemy jako błędne i ustawiamy jako NaN
# num_cols = ['population', 'population_density', 'human_development_index',
#            'gdp_usd', 'gdp_per_capita_usd', 'area_sq_km', 'life_expectancy']
# for col in num_cols:
#     df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')
#     df_clean.loc[df_clean[col] < 0, col] = np.nan

df_clean

In [28]:
#  4.1. Chcemy posiadać podstawowe dane o wszystkich krajach świata, które będą zrozumiałe dla człowieka oraz uniwersalne i 
#  potencjalnie przyszłościowe do dalszego przetwarzania.

countries_cols = [
    'country_code', 'country_name', 'population', 'population_male', 'population_female', 'population_density',
    'human_development_index', 'gdp_usd', 'gdp_per_capita_usd', 'area_sq_km', 'life_expectancy'
]
df_countries = df_clean[countries_cols].drop_duplicates()
# Opcjonalnie: usuwamy wiersze, gdzie brakuje kluczowych informacji o kraju
df_countries = df_countries.dropna(subset=['population', 'population_density', 'gdp_usd'])
# Propozycja naprawy błędnych danych: np. dla kolumn numerycznych warto sprawdzić, czy nie występują wartości ujemne
# i w razie ich wystąpienia zastąpić je np. zerem lub wartością mediany (tutaj tylko komentarz)

# Zapis do pliku CSV
df_countries.to_csv('4_1_countries_data.csv', index=False)

#df_countries

In [29]:
# 4.2. Chcemy wygenerować statystyki dotyczące zachorowań na COVID-19 na całym świecie.

cases_cols = [
    'location_key', 'date', 'country_code', 'country_name', 
    'new_confirmed', 'cumulative_confirmed', 'new_tested', 'cumulative_tested',
    'new_recovered', 'new_hospitalized_patients'
]
df_cases = df_clean[cases_cols].drop_duplicates()
df_cases = df_cases.dropna(subset=['date', 'new_confirmed', 'cumulative_confirmed']) # Usuwanie wierszy z brakującymi wartosciami
df_cases.to_csv('4_2_global_covid_cases.csv', index=False)

#df_cases

In [30]:
# 4.3. Chcemy poznać efekty COVID-19 poprzez uwypuklenie problemu śmiertelności ludzi spowodowanej wirusem.

mortality_cols = [
    'location_key', 'date', 'country_code', 'country_name', 
    'new_deceased', 'cumulative_deceased'
]
df_mortality = df_clean[mortality_cols].drop_duplicates()
df_mortality = df_mortality.dropna(subset=['date', 'new_deceased', 'cumulative_deceased'])
df_mortality.to_csv('4_3_covid_mortality.csv', index=False)

#df_mortality

In [32]:
# 4.4. Chcemy zaobserwować trendy i zależności dotyczące szczepień na COVID-19.

vaccination_cols = [
    'location_key', 'date', 'country_code', 'country_name', 
    'new_persons_vaccinated', 'cumulative_persons_vaccinated', 
    'new_persons_fully_vaccinated', 'cumulative_persons_fully_vaccinated',
    'population_age_00_09', 'population_age_10_19', 'population_age_20_29', 'population_age_30_39',
    'population_density', 'smoking_prevalence', 'diabetes_prevalence', 'life_expectancy',
    'cumulative_vaccine_doses_administered', 'new_vaccine_doses_administered'
]
df_vaccinations = df_clean[vaccination_cols].drop_duplicates()
df_vaccinations = df_vaccinations.dropna(subset=['date'])
df_vaccinations.to_csv('4_4_vaccination_trends.csv', index=False)

#df_vaccinations

In [33]:
# 4.5. Zdefiniuj własny dodatkowy przypadek.

# Przykładowo: Analiza związku między restrykcjami rządowymi (stringency_index) a liczbą nowych zachorowań
# Można wybrać coś ciekawszego tho
df_custom = df_clean[['date', 'country_name', 'stringency_index']].copy()
# Usuwamy rekordy, w których brakuje krytycznych informacji
df_custom = df_custom.drop_duplicates().dropna(subset=['date', 'stringency_index'])
df_custom.to_csv('4_5_custom_case.csv', index=False)

#df_custom

In [34]:
#5.0
# Dataframey powstałe w części 4
# df_countries         - dane statyczne o krajach (4.1)
# df_cases             - dane dotyczące zachorowań (4.2)
# df_mortality         - dane dotyczące śmiertelności (4.3)
# df_vaccinations      - dane dotyczące szczepień (4.4)
# df_custom           - dane customowe(4.5)

# 1. Łączenie danych czasowych
# Klucz łączący to: "location_key", "date", "country_code", "country_name"

# Łączymy dane dotyczące zachorowań i śmiertelności
df_time_series = pd.merge(
    df_cases, df_mortality,
    on=["location_key", "date", "country_code", "country_name"],
    how="outer"
)

# Dołączamy dane dotyczące szczepień
df_time_series = pd.merge(
    df_time_series, df_vaccinations,
    on=["location_key", "date", "country_code", "country_name"],
    how="outer"
)

# Upewnij się, że kolumna 'date' w obu DataFrame’ach jest w formacie datetime64[ns]
df_time_series['date'] = pd.to_datetime(df_time_series['date'])
df_custom['date'] = pd.to_datetime(df_custom['date'])

# Dołączamy dane dotyczące testów
df_time_series = pd.merge(
    df_time_series, df_custom,
    on=["date", "country_name"],
    how="outer"
)

# df_countries nie zawiera kolumny 'date', dlatego łączymy je na podstawie wspólnych kluczy: "country_code" i "country_name"
df_final = pd.merge(
    df_time_series, df_countries,
    on=["country_code", "country_name"],
    how="left"
)

# Usuwamy ewentualne duplikaty
df_final = df_final.drop_duplicates()

# Sortujemy dane – najczęściej po kodzie kraju i dacie, by mieć ujednoliconą strukturę
df_final = df_final.sort_values(by=["country_code", "date"])

# Zapisujemy wynik do pliku CSV
df_final.to_csv("5.0_combined_covid_data.csv", index=False)

#df_final

In [35]:
#6.0
# 1. Wczytanie danych z części 5
df_covid = pd.read_csv("5.0_combined_covid_data.csv", parse_dates=["date"])

# 2. Wczytanie danych z world_countries.csv
df_world = pd.read_csv("world_countries.csv")
# Zmieniamy nazwę kolumny "Country/Territories" na "country_name" dla ułatwienia łączenia
df_world.rename(columns={"Country/Territory": "country_name"}, inplace=True)

# 3. Wczytanie danych z GDP.csv
df_gdp = pd.read_csv("GDP.csv")
# Zmieniamy nazwę kolumny "Country Name" na "country_name"
df_gdp.rename(columns={"Country Name": "country_name"}, inplace=True)

# 4. Normalizacja kluczy łączenia (pełne nazwy krajów) we wszystkich DataFrame'ach
df_covid["country_name"] = df_covid["country_name"].str.strip().str.lower()
df_world["country_name"] = df_world["country_name"].str.strip().str.lower()
df_gdp["country_name"] = df_gdp["country_name"].str.strip().str.lower()

# 5. Dla danych covidowych wyodrębniamy rok z kolumny "date", by móc łączyć z danymi PKB
df_covid["year"] = df_covid["date"].dt.year

# 6. Łączenie danych
# 6.1. Łączymy dane covidowe z danymi krajowymi (world_countries.csv) – łączymy po "country_name"
df_merged = pd.merge(df_covid, df_world, on="country_name", how="left")

# 6.2. Łączymy wynik z danymi PKB. W df_gdp kolumna z rokiem to zazwyczaj "Year", więc łączymy:
df_merged = pd.merge(df_merged, df_gdp, left_on=["country_name", "year"], 
                     right_on=["country_name", "Year"], how="left")
# Połączone dane mają już dwie kolumny określające rok, więc możemy usunąć zbędną kolumnę "Year":
df_merged.drop(columns=["Year"], inplace=True)

# 7. Usunięcie zbędnych kolumn: 'area_sq_km', 'Country Code', 'Value'
df_merged = df_merged.drop(columns=['area_sq_km', 'Country Code', 'Value'], errors='ignore')

# 8. Finalne czyszczenie danych – usunięcie duplikatów itp.
df_merged.drop_duplicates(inplace=True)

# df_pivoted = df_merged.pivot(['country_code', 'country_name'],)
# 9. Zapisanie wyniku do pliku CSV
df_merged.to_csv("6.0_combined_covid_world_gdp_data.csv", index=False)

#Dane z części 5 oraz pliki world_countries.csv i GDP.csv zostały połączone i zapisane do pliku combined_covid_world_gdp_data.csv."